# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
