# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0002_coordonnees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnees',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=19, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coordonnees',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=19, max_digits=20, null=True),
        ),
    ]
