# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0003_auto_20160822_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnees',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordonnees',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordonnees',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
