# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0004_auto_20160822_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordonnees',
            name='nom',
        ),
    ]
